sudo: required
services:
    - docker

before_install:
    - docker build -t peterboot/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true peter-boot/docker-react npm run test